//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// nPOP.rc で使用
//
#define LVS_REPORT                      0x0001
#define LVS_SINGLESEL                   0x0004
#define IDC_BUTTON_DELETE               4
#define IDC_BUTTON_MAIL                 5
#define LVS_SHOWSELALWAYS               0x0008
#define IDR_MENU_WINDOW                 101
#define IDD_DIALOG_POP                  102
#define IDI_ICON_MAIN                   103
#define IDR_ACCELERATOR                 105
#define IDI_ICON_DOWN                   107
#define IDI_ICON_DEL                    108
#define IDI_ICON_NON                    109
#define IDI_ICON_READ                   110
#define IDR_MENU_VIEW                   112
#define IDB_TOOLBAR                     116
#define IDB_TOOLBAR_VIEW                117
#define IDD_DIALOG_OPTION_RECV          119
#define IDD_DIALOG_INPUTPASS            120
#define IDI_ICON_NEW                    121
#define IDR_MENU_EDIT                   122
#define IDD_DIALOG_SETSEND              123
#define IDB_TOOLBAR_EDIT                128
#define IDI_ICON_SENDMAIL               129
#define IDI_ICON_SEND                   130
#define IDR_ACCELERATOR_EDIT            131
#define IDR_ACCELERATOR_VIEW            132
#define IDD_DIALOG_SMTP                 134
#define IDD_DIALOG_MAKE                 135
#define IDD_DIALOG_OPTION_SEND          138
#define IDD_DIALOG_OPTION_MAKE          139
#define IDD_DIALOG_CC                   140
#define IDD_DIALOG_ETCHEAD              141
#define IDD_DIALOG_OPTION_CHECK         142
#define IDD_DIALOG_ADDRESS              144
#define IDD_DIALOG_ADDRESS_EDIT         145
#define IDD_DIALOG_MSG                  146
#define IDR_MENU_POPUP                  148
#define IDD_DIALOG_OPTION_ETC           149
#define IDR_MENU_WINDOW_HPC             153
#define IDD_DIALOG_FILTER               154
#define IDD_DIALOG_FILTER_EDIT          155
#define IDD_DIALOG_INITMAILBOX          160
#define IDI_ICON_CHECK                  162
#define IDI_ICON_NOCHECK                164
#define IDI_ICON_CLIP                   168
#define IDD_DIALOG_ATTACH               171
#define IDD_DIALOG_MAILPROP             173
#define IDD_DIALOG_FIND                 174
#define IDB_TOOLBAR_CE                  180
#define IDR_MENU_EDIT_HPC               181
#define IDR_MENU_VIEW_HPC               182
#define IDD_DIALOG_SETSMTPAUTH          183
#define IDD_DIALOG_ATTACH_NOTICE        184
#define IDD_DIALOG_POP_HPC              186
#define IDD_DIALOG_OPTION_RECV_HPC      187
#define IDD_DIALOG_SETSSL               189
#define IDD_DIALOG_ENCODE               191
#define IDB_TOOLBAR_32                  193
#define IDB_TOOLBAR_48                  194
#define IDB_TOOLBAR_VIEW_32             195
#define IDB_TOOLBAR_VIEW_48             196
#define IDB_TOOLBAR_EDIT_32             197
#define IDB_TOOLBAR_EDIT_48             198
#define IDC_EDIT_SERVER                 1001
#define IDC_EDIT_NAME                   1002
#define IDC_EDIT_TITLE                  1003
#define IDC_EDIT_MAILADDRESS            1003
#define IDC_EDIT_PORT                   1004
#define IDC_EDIT_USER                   1005
#define IDC_EDIT_PASS                   1006
#define IDC_CHECK_APOP                  1008
#define IDC_EDIT_READLINE               1009
#define IDC_CHECK_CYCLIC                1009
#define IDC_RADIO_NOSAVE                1010
#define IDC_CHECK_SSL                   1010
#define IDC_RADIO_HEADSAVE              1011
#define IDC_RADIO_ALLSAVE               1012
#define IDC_EDIT_TO                     1012
#define IDC_COMBO_SMTP                  1013
#define IDC_EDIT_SIG                    1014
#define IDC_CHECK_SHOWHEAD              1015
#define IDC_EDIT_QUOTCHAR               1016
#define IDC_CHECK_LISTDOWNLOAD          1016
#define IDC_EDIT_REHEAD                 1017
#define IDC_CHECK_NORETR                1017
#define IDC_CHECK_QBREAK                1018
#define IDC_CHECK_AUTOQUOT              1019
#define IDC_EDIT_BREAKCNT               1020
#define IDC_LIST_CC                     1021
#define IDC_RADIO_CC                    1023
#define IDC_RADIO_BCC                   1024
#define IDC_BUTTON_ADD                  1025
#define IDC_BUTTON_CC                   1026
#define IDC_BUTTON_EDIT                 1026
#define IDC_EDIT_REPLYTO                1027
#define IDC_BUTTON_FLAG                 1027
#define IDC_BUTTON_ETC                  1028
#define IDC_CHECK_SENDMESSAGEID         1029
#define IDC_BUTTON_ATTACH               1029
#define IDC_CHECK_SHIWNEWMESSAGE        1030
#define IDC_CHECK_SELECTSENDBOX         1030
#define IDC_CHECK_SHIWNOMESSAGE         1031
#define IDC_CHECK_POPBEFORESMTP         1031
#define IDC_CHECK_SENDDATE              1031
#define IDC_CHECK_AUTOCHECK             1032
#define IDC_CHECK_LOGINONLY             1032
#define IDC_EDIT_AUTOCHECKTIME          1033
#define IDC_BUTTON_UNINSTALL            1034
#define IDC_LIST_ADDRESS                1035
#define IDC_BUTTON_TO                   1037
#define IDC_EDIT_COMMENT                1038
#define IDC_STATIC_ICON                 1038
#define IDC_CHECK_SOUND                 1039
#define IDC_EDIT_CONTENT2               1039
#define IDC_CHECK_STARTCHECK            1040
#define IDC_CHECK_IGNOREERROR           1041
#define IDC_CHECK_SHOWTRAYICON          1042
#define IDC_CHECK_SENDIGNOREERROR       1042
#define IDC_CHECK_MINSIZEHIDE           1043
#define IDC_CHECK_EXECSOUND             1043
#define IDC_CHECK_CLOSEHIDE             1044
#define IDC_CHECK_CHECKAFTERUPDATE      1044
#define IDC_CHECK_SHOWPASS              1045
#define IDC_CHECK_MOVEALLMAILBOX        1046
#define IDC_CHECK_STARTPASS             1047
#define IDC_CHECK_VIEWCLOSE             1048
#define IDC_BUTTON_UP                   1052
#define IDC_LIST_FILTER                 1053
#define IDC_BUTTON_DOWN                 1054
#define IDC_CHECK_FILTER                1055
#define IDC_BUTTON_ANDOR                1056
#define IDC_CHECK_FLAG                  1057
#define IDC_COMBO_HEAD1                 1058
#define IDC_COMBO_HEAD2                 1059
#define IDC_EDIT_CONTENT1               1060
#define IDC_CHECK_MYADDR2BCC            1061
#define IDC_COMBO_ACTION                1061
#define IDC_STATIC_TITLE                1063
#define IDC_EDIT_GETNUM                 1064
#define IDC_RADIO_FIRSTGET              1065
#define IDC_RADIO_SETGET                1066
#define IDC_CHECK_QUOTATION             1066
#define IDC_CHECK_SMTPAUTH              1068
#define IDC_LIST_FILE                   1075
#define IDC_CHECK_ENCODETYPE            1078
#define IDC_BUTTON_ADDADDRESS           1079
#define IDC_BUTTON_REPLY                1080
#define IDC_EDIT_FIND                   1080
#define IDC_BUTTON_NEW                  1081
#define IDC_CHECK_CASE                  1081
#define IDC_CHECK_ALL                   1082
#define IDC_CHECK_SUBJECT               1083
#define IDC_BUTTON_SETAUTH              1083
#define IDC_CHECK_POP                   1084
#define IDC_CHECK_TMPPASS               1085
#define IDC_EDIT_SOUND                  1087
#define IDC_RADIO_OPEN                  1087
#define IDC_BUTTON_SOUND_BROWS          1088
#define IDC_RADIO_SAVE                  1088
#define IDC_BUTTON_SOUND_PLAY           1089
#define IDC_STATIC_MAILCNT              1089
#define IDC_STATIC_FILENAME             1089
#define IDC_EDIT_EXECSOUND              1090
#define IDC_STATIC_MAILSIZE             1090
#define IDC_BUTTON_SETSSL               1090
#define IDC_STATIC_TYPE                 1090
#define IDC_COMBO_SSLTYPE               1091
#define IDC_STATIC_FROM                 1091
#define IDC_CHECK_VERIFY                1092
#define IDC_COMBO_CHARSET_H             1093
#define IDC_COMBO_ENCODE_H              1094
#define IDC_BUTTON_ENCODE               1096
#define IDC_COMBO_CHARSET               1097
#define IDC_COMBO_ENCODE                1098
#define IDC_COMBO_AUTHTYPE              1098
#define LVS_NOSORTHEADER                0x8000
#define ID_MENUITEM_RECV                40001
#define ID_MENUITE_QUIT                 40002
#define ID_KEY_ESC                      40004
#define ID_MENUITEM_OPEN                40005
#define ID_MENUITEM_DOWNMARK            40006
#define ID_MENUITEM_DELMARK             40007
#define ID_MENUITEM_EXEC                40008
#define ID_MENUITEM_UNMARK              40009
#define ID_MENUITEM_ALLSELECT           40010
#define ID_KEY_ENTER                    40011
#define ID_MENUITEM_CLOSE               40012
#define ID_MENUITEM_NEXTMAIL            40013
#define ID_MENUITEM_NEXTNOREAD          40014
#define ID_MENUITEM_PREVMAIL            40015
#define ID_MENUITEM_STOP                40016
#define ID_KEY_CTRLENTER                40017
#define ID_MENUITEM_DELETE              40018
#define ID_MENUITEM_LISTINIT            40019
#define ID_MENUITEM_ABOUT               40020
#define ID_MENUITEM_ICONSORT            40021
#define ID_MENUITEM_ADDMAILBOX          40022
#define ID_MENUITEM_DELETEMAILBOX       40023
#define ID_MENUITEM_CHANGEMAILBOX       40024
#define ID_MENUITE_SAVECOPY             40025
#define ID_MENUITEM_WORDBREAK           40026
#define ID_MENUITEM_OPTION              40027
#define ID_MENUITEM_REMESSEGE           40028
#define ID_KEY_TAB                      40030
#define ID_MENUITEM_NEWMAIL             40031
#define ID_MENUITEM_SEND                40032
#define ID_MENUITEM_SENDBOX             40033
#define ID_MENUITEM_SENDINFO            40034
#define ID_KEY_ALTUP                    40035
#define ID_KEY_ALTDOWN                  40036
#define ID_KEY_UP                       40039
#define ID_KEY_DOWN                     40040
#define ID_KEY_LEFT                     40041
#define ID_KEY_RIGHT                    40042
#define WM_NOMSG                        40043
#define ID_MENUITEM_COPY                40044
#define ID_MENUITEM_CUT                 40046
#define ID_MENUITEM_PASTE               40047
#define ID_MENUITEM_SETMAILBOX          40048
#define ID_MENUITEM_UNDO                40049
#define ID_MENUITEM_ALLCHECK            40050
#define ID_MENUITEM_ADDRESS             40051
#define ID_MENUITEM_RESTORE             40054
#define ID_MENUITEM_RAS_CONNECT         40060
#define ID_MENUITEM_RAS_DISCONNECT      40061
#define ID_KEY_SHOWMENU                 40067
#define ID_MENUITEM_ALLREMESSEGE        40068
#define ID_MENUITEM_MOVEUPMAILBOX       40069
#define ID_MENUITEM_MOVEDOWNMAILBOX     40070
#define ID_MENUITEM_READMAIL            40071
#define ID_MENUITEM_NOREADMAIL          40072
#define ID_MENUITEM_THREADVIEW          40074
#define ID_MENUITEM_ALLEXEC             40075
#define ID_MENUITEM_SHOW_DATE           40078
#define ID_MENUITEM_SHOWLASTWINDOW      40080
#define ID_MENUITEM_SAVE                40085
#define ID_MENUITEM_FILEOPEN            40086
#define ID_MENUITEM_PROP                40087
#define ID_MENUITEM_FIND                40088
#define ID_MENUITEM_NEXTFIND            40090
#define ID_MENUITEM_VIEW                40091
#define ID_MENUITEM_LAN                 40092
#define ID_MENUITEM_ATTACH              40094
#define ID_MENUITEM_FORWARD             40095
#define ID_MENUITEM40095                40095
#define ID_MENUITEM_FONT                40096
#define ID_MENUITEM_ENCODE              40097
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         40098
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
